name: Add/Remove Snowflakes

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 11 *' # November 1st, 00:00 UTC
    - cron: '0 0 1 1 *'  # January 1st, 00:00 UTC

jobs:
  update-snowflakes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Add or remove snowflakes
        run: |
          SNOWFLAKE_HTML="$(cat snowflakes.html)"
          for f in $(find . -name '*.html'); do
            if grep -q 'class="snowflakes"' "$f"; then
              sed -i '/<div class="snowflakes" aria-hidden="true">/,/<\/div>/d' "$f"
            else
              awk -v snowflakes="$SNOWFLAKE_HTML" '
                /<\/body>/ { print snowflakes }
                { print }
              ' "$f" > "$f.tmp" && mv "$f.tmp" "$f"
            fi
          done

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if [ "$(date +%m-%d)" = "11-01" ]; then
            git commit -m "Add snowflakes for the holidays" || echo "No changes to commit"
          elif [ "$(date +%m-%d)" = "01-01" ]; then
            git commit -m "Remove snowflakes after holidays" || echo "No changes to commit"
          fi
          git push
